version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    groups:
      npm-non-major:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    reviewers:
      - 'naveen'
    labels:
      - 'dependencies'
      - 'automated'
